# Generated by Django 3.0.6 on 2020-05-18 22:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Imya')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Vozrast')),
                ('description', models.TextField(verbose_name='Opisanie')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Izobrajenie')),
            ],
            options={
                'verbose_name': 'Actors and directors',
                'verbose_name_plural': 'Actors and directors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Categoria')),
                ('description', models.TextField(verbose_name='Opisanie')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Imya')),
                ('description', models.TextField(verbose_name='Opisanie')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nazvanie')),
                ('tagline', models.CharField(default='', max_length=100, verbose_name='Slogan')),
                ('description', models.TextField(verbose_name='Opisanie')),
                ('poster', models.ImageField(upload_to='movies/', verbose_name='Poster')),
                ('year', models.PositiveSmallIntegerField(default=2020, verbose_name='Date out')),
                ('country', models.CharField(max_length=50, verbose_name='Strana')),
                ('world_premiere', models.DateField(default=datetime.date.today, verbose_name='Primiera v mire')),
                ('budget', models.PositiveIntegerField(default=0, help_text='summa v baksah', verbose_name='Budjet')),
                ('fees_in_usa', models.PositiveIntegerField(default=0, help_text='summa v baksah', verbose_name='Sbori v USA')),
                ('fees_in_world', models.PositiveIntegerField(default=0, help_text='summa v baksah', verbose_name='Sbori v USA')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Chernovik')),
                ('actors', models.ManyToManyField(related_name='film_actor', to='movies.Actor', verbose_name='actor')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.Category', verbose_name='Categoriya')),
                ('directors', models.ManyToManyField(related_name='film_director', to='movies.Actor', verbose_name='director')),
                ('genres', models.ManyToManyField(to='movies.Genre', verbose_name='Janri')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmy',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Znachenie')),
            ],
            options={
                'verbose_name': 'Zvezda raytinga',
                'verbose_name_plural': 'Zvezdi raytinga',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Imya')),
                ('text', models.TextField(max_length=5000, verbose_name='Text')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='Film')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.Reviews', verbose_name='Roditel')),
            ],
            options={
                'verbose_name': 'Otziv',
                'verbose_name_plural': 'Otzivi',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP adress')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='film')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.RatingStar', verbose_name='zvezda')),
            ],
            options={
                'verbose_name': 'Rayting',
                'verbose_name_plural': 'Raytingi',
            },
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Zagolovok')),
                ('description', models.TextField(verbose_name='Opisanie')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Izobrajenie')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'Shot from film',
                'verbose_name_plural': 'Shots from film',
            },
        ),
    ]
